default_model = "GEMINI"
prompt = """
Analyze the following git diff and generate a concise and meaningful commit message summarizing the changes.
The commit message should follow best practices, including a short title and an optional detailed description if necessary.
Requirements:
  Title: 50 characters or less, summarizing the change.
  Optional Description: If the change requires context, provide a brief explanation in the body.

git diff:

"""

[api_keys]
gemini_api_key = "AIzaSyCZg0O7Mc98GeS-xnTb2pijLgaUDLWIidk"
deepseek_api_key = "api_key"
